---

- name: Get splunk-otel-collector latest version
  ansible.windows.win_get_url:
    url: "{{win_base_url}}/splunk-otel-collector/msi/{{package_stage}}/latest.txt"
    dest: "%TEMP%"
    proxy_password: "{{ win_proxy_password | default(omit) }}"
    proxy_url: "{{ win_proxy_url | default(omit) }}"
    proxy_username: "{{ win_proxy_username | default(omit) }}"
    use_proxy: "{{ win_use_proxy }}"
  register: latest
  when: splunk_otel_collector_version == "latest"

- name: get content of remote file
  slurp:
    src: "{{latest.dest}}"
  register: version
  when: splunk_otel_collector_version == "latest"

- name: decode remote file content for latest version
  set_fact:
    splunk_otel_collector_version: "{{version.content | b64decode }}"
  when: splunk_otel_collector_version == "latest"

- name: Get splunk-otel-collector for windows
  ansible.windows.win_get_url:
    url: "{{win_base_url}}/splunk-otel-collector/msi/{{package_stage}}/splunk-otel-collector-\
          {{splunk_otel_collector_version}}-amd64.msi"
    dest: "%TEMP%"
    proxy_password: "{{ win_proxy_password | default(omit) }}"
    proxy_url: "{{ win_proxy_url | default(omit) }}"
    proxy_username: "{{ win_proxy_username | default(omit) }}"
    use_proxy: "{{ win_use_proxy }}"
  register: otel_msi_package

- name: Install splunk-otel-collector-msi
  ansible.windows.win_package:
    path: "{{otel_msi_package.dest}}"
    state: present
    arguments: >-
      SPLUNK_ACCESS_TOKEN="{{ splunk_access_token }}"
      SPLUNK_API_URL="{{ splunk_api_url if splunk_api_url != '' else omit }}"
      GOMEMLIMIT="{{ gomemlimit if gomemlimit != '' else omit }}"
      SPLUNK_BUNDLE_DIR="{{ splunk_bundle_dir if splunk_bundle_dir != '' else omit }}"
      SPLUNK_COLLECTD_DIR="{{ splunk_collectd_dir if splunk_collectd_dir != '' else omit }}"
      SPLUNK_CONFIG="{{ splunk_otel_collector_config if splunk_otel_collector_config != '' else omit }}"
      SPLUNK_INGEST_URL="{{ splunk_ingest_url if splunk_ingest_url != '' else omit }}"
      SPLUNK_HEC_TOKEN="{{ splunk_hec_token if splunk_hec_token != '' else omit }}"
      SPLUNK_HEC_URL="{{ splunk_hec_url if splunk_hec_url != '' else omit }}"
      SPLUNK_LISTEN_INTERFACE="{{ splunk_listen_interface if splunk_listen_interface != '' else omit }}"
      SPLUNK_MEMORY_TOTAL_MIB="{{ splunk_memory_total_mib if splunk_memory_total_mib != '' else omit }}"
      SPLUNK_REALM="{{ splunk_realm if splunk_realm != '' else omit }}"
      SPLUNK_TRACE_URL="{{ splunk_trace_url if splunk_trace_url != '' else omit }}"

- name: Merge custom config into the default config
  ansible.builtin.import_tasks: config_override.yml
  when: splunk_config_override != ''

- name: Copy the custom config
  ansible.windows.win_copy:
    content: '{{ updated_config | to_nice_yaml (indent=2) }}'
    dest: "{{ splunk_otel_collector_config }}"
  when: splunk_config_override != ''

- name: Push Custom Config file for splunk-otel-collector, If provided
  ansible.windows.win_template:
    src: "{{splunk_otel_collector_config_source}}"
    dest: "{{splunk_otel_collector_config}}"
  when: splunk_otel_collector_config_source != ""
