---
# handlers file for splunk-otel-collector

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  listen:
    - restart splunk-otel-collector
    - restart td-agent

- name: Restart td-agent
  ansible.builtin.service:
    name: td-agent
    state: restarted
  when:
    - install_fluentd and fluentd_supported and (start_service | default(true) | bool)
  listen: "restart td-agent"

- name: Restart Splunk OpenTelemetry Collector
  ansible.builtin.service:
    name: splunk-otel-collector
    state: restarted
  listen: "restart splunk-otel-collector"
  when:
    - (start_service | default(true) | bool)

- name: Restart Splunk OpenTelemetry Collector for windows
  ansible.windows.win_shell: |
    Get-Item HKLM:\SYSTEM\CurrentControlSet\Services\splunk-otel-collector
    Restart-Service splunk-otel-collector
    Get-WinEvent -Log Application -MaxEvents 15 | Format-List TimeCreated, ProviderName, Message
    Get-WinEvent -Log System -MaxEvents 15 | Format-List TimeCreated, ProviderName, Message
  listen: "restart windows splunk-otel-collector"
  when:
    - (start_service | default(true) | bool)

- name: Restart td-agent for windows
  ansible.windows.win_service:
    name: fluentdwinsvc
    state: restarted
  listen: "restart windows fluentdwinsvc"
  when:
    - (start_service | default(true) | bool)

- name: Reset IIS
  ansible.windows.win_shell: |
    try {
      Get-Command iisreset.exe
    } Catch {
      Exit
    }
    & { iisreset.exe }
  listen: "reset iis"
  when:
    - install_signalfx_dotnet_auto_instrumentation and signalfx_dotnet_auto_instrumentation_iisreset
